### ISSUE TITLE
GA401IH Variant

### ISSUE THREAD

**Issue by edkozuto** [zllovesuki/G14Manager#38]
Here's DSDT made with SSDTTime, don't know how to make SSDT from it though.
[GA401IH-DSDT.zip](https://github.com/zllovesuki/G14Manager/files/5114839/GA401IH-DSDT.zip)

**Comment by zllovesuki** [comment]
Although it looks like it is missing the SSDT table, the DSDT looks identical asides from the location of the TPM modules. I will update the README to reflect compatibility.
