### ISSUE TITLE
Charge Limit Rate isn't reliable especially waking up from hibernate

### ISSUE THREAD

**Issue by erikjoya** [zllovesuki/G14Manager#42]
I notice the charge limit rate will stop applying after waking up from hibernate.
Using 0.21

**Comment by zllovesuki** [comment]
I think the charge limit stays with the EC memory, and once the board is off power, it got clear. I will prioritize reapplying configs on wake.

**Comment by erikjoya** [comment]
Thanks for the quick response! I'll use myasus as a supplement for now.
