### ISSUE TITLE
Issue: PgUp/PgDn and ROG key are not working

### ISSUE THREAD

**Issue by edkozuto** [zllovesuki/G14Manager#44]
When setting up a task in Task Scheduler to launch G14Manager at startup with `-experimental -rog "Taskmgr.exe"`, the PgUp/PgDn and ROG key are not working.
![image](https://user-images.githubusercontent.com/2198297/91460157-27452900-e890-11ea-89ad-6291d88c7f82.png)
![image](https://user-images.githubusercontent.com/2198297/91460179-3035fa80-e890-11ea-8a8b-fcecbb835515.png)
![image](https://user-images.githubusercontent.com/2198297/91460216-39bf6280-e890-11ea-8ee8-03bde4f893fc.png)
![image](https://user-images.githubusercontent.com/2198297/91460240-45128e00-e890-11ea-9ef2-829e0f56f6fa.png)
![image](https://user-images.githubusercontent.com/2198297/91460265-4e035f80-e890-11ea-9d4b-f75ab418d3b3.png)

**Comment by zllovesuki** [comment]
When you say they don’t work, are they just not working in certain applications, or flat out does not work in any program? 

Also, G14Manager should run as the user and on user login, instead of system startup

**Comment by edkozuto** [comment]
Setting to launch on log on of specific user fixed the issue, thanks!

**Comment by zllovesuki** [comment]
Possible issue: if the application that you are using uses DirectInput (like many games), it reads from the HID directly, and the SendInput approach will not work. A keyboard filter driver is needed to make it work with DirectInput but I think that’s way too out of scope for this purpose.
