### ISSUE TITLE
Cannot find target power plan

### ISSUE THREAD

**Issue by crypto512** [zllovesuki/G14Manager#45]
Well done for the tool.
I've uninstalled all Asus stuff and in the end I've the message " Cannot find target power plan".
Can you clarify what is mandatory to keep and what can be uninstalled ?

**Comment by zllovesuki** [comment]
Please take a look at README. Currently due to how the fan curves are setup, it expects “High Performance” and “Power Saver” to be available in order for G14Manager to start. This will be decoupled in a future release

**Comment by crypto512** [comment]
Do you know which Asus module create them ?

**Comment by crypto512** [comment]
I've just done export, uninstall, import of power plan and it works!
https://www.windowscentral.com/how-export-and-import-power-plan-multiple-windows-10-pcs
