### ISSUE TITLE
Frozen during sleep

### ISSUE THREAD

**Issue by crypto512** [zllovesuki/G14Manager#46]
after installing 0.2.2 found my G14 two times in sleep mode with fan at high rate and completely frozen. (hard power down required). Never saw this issue before 0.2.2.

**Comment by zllovesuki** [comment]
Does it happen when you attempt to wake the laptop from suspend?

**Comment by crypto512** [comment]
No I found it with fan at high rate and I cannot wake the laptop from suspend.

**Comment by zllovesuki** [comment]
Cannot wake from suspend is an issue with current laptop firmware, it is not caused by the G14Manager.

**Comment by crypto512** [comment]
Never had it without G14manager maybe it happens less without it. Is it possilbe to be related to the latest change about wakeup refresh of the configuration ?

**Comment by zllovesuki** [comment]
Negative. Similar issues arise when I was using "stock" software configuration. The similar issues on a few Asus Ryzen laptops, and we can only wait for Asus to fix the firmware.

**Comment by zllovesuki** [comment]
Asus released a new firmware 217. Please check if the new firmware fixes the issue

**Comment by crypto512** [comment]
I've reinstalled waiting a little bit to report.
I've kept installed Armory Crate, Armory Crate Service and stopped all services.
If I remove all ASUS software G14Manager will not start and I need to reinstall most of them to be able to restore the profiles.

**Comment by zllovesuki** [comment]
Customizable profile is in the works. In the meantime, you can manually create the missing profiles, and manually tweak them.

**Comment by crypto512** [comment]
Great.
I've just done export, uninstall, import of power plan and it works!
https://www.windowscentral.com/how-export-and-import-power-plan-multiple-windows-10-pcs
