### ISSUE TITLE
Chore: Investigate AniMe Matrix Control Integration

### ISSUE THREAD

**Issue by zllovesuki** [zllovesuki/G14Manager#57]
Community member @thesacredmoocow has written a ~~C#~~ C++ program (https://github.com/thesacredmoocow/G14MatrixControl) for controlling the AniMe Matrix LEDs. Investigate if porting to Go is viable, or integrating as binary with gRPC communication is viable.

**Comment by thesacredmoocow** [comment]
Originally written in c++, and it uses the winUSB part of the windows sdk, so long as that's present it can be ported.

**Comment by zllovesuki** [comment]
I meant to say C++. Somehow I always thought of .sln are C# projects 😂

**Comment by zllovesuki** [comment]
I wonder if I can simply add C bindings in Go, then let `cgo` handles the rest.

**Comment by zllovesuki** [comment]
https://github.com/flukejones/rog-core/blob/master/rog-core/src/animatrix_control.rs but for Linux using `libusb` driver

**Comment by zllovesuki** [comment]
Syscalling via DLL is successful: https://github.com/zllovesuki/G14Manager/commits/matrix_control

![image](https://user-images.githubusercontent.com/298453/101295850-f9b93580-3817-11eb-8b64-319c1940127a.png)
