### ISSUE TITLE
0.4 process abort on display 

### ISSUE THREAD

**Issue by crypto512** [zllovesuki/G14Manager#67]
0.4 exit with error:

C:\Program Files (x86)\G14Manager>G14Manager.debug.exe
2021/04/01 13:37:30 G14Manager version: v0.4.0-debug
Available devices:
\\.\DISPLAY1 - AMD Radeon(TM) Graphics - 60 Hz - active
\\.\DISPLAY2 - AMD Radeon(TM) Graphics - 0 Hz - inactive
\\.\DISPLAY3 - AMD Radeon(TM) Graphics - 0 Hz - inactive
\\.\DISPLAY4 - AMD Radeon(TM) Graphics - 0 Hz - inactive
\\.\DISPLAY5 - NVIDIA GeForce RTX 2060 with Max-Q Design - 144 Hz - active - primary
\\.\DISPLAY6 - NVIDIA GeForce RTX 2060 with Max-Q Design - 0 Hz - inactive
\\.\DISPLAY7 - NVIDIA GeForce RTX 2060 with Max-Q Design - 0 Hz - inactive
\\.\DISPLAY8 - NVIDIA GeForce RTX 2060 with Max-Q Design - 0 Hz - inactive
No primary display found2021/04/01 13:37:30 [supervisor] cannot get dependencies

**Comment by zllovesuki** [comment]
Well, I made an assumption about the internal display being the primary display. I will fix this later today.

**Comment by zllovesuki** [comment]
v0.4.1 should fix the issue: https://github.com/zllovesuki/G14Manager/releases/tag/v0.4.1
