### ISSUE TITLE
G14Manager version: v0.4.1 does not start

### ISSUE THREAD

**Issue by foxperience** [zllovesuki/G14Manager#69]
2021/04/02 11:01:20 G14Manager version: v0.4.1-debug
2021/04/02 11:01:20 [gRPCSupervisor] starting responder loop
2021/04/02 11:01:20 [pprof] debugging server available at 127.0.0.1:9969
2021/04/02 11:01:20 [VersionChecker] starting checker loop
2021/04/02 11:01:20 [VersionChecker] checking for new version
2021/04/02 11:01:20 [notifier] starting notify loop
2021/04/02 11:01:20 [gRPCSupervisor] exiting ManagerResponder
2021/04/02 11:01:20 [gRPCServer] Failed to listen for connections: listen tcp 127.0.0.1:9963: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2021/04/02 11:01:20 [VersionChecker] error checking for new version: Get "https://api.github.com/repos/zllovesuki/G14Manager/releases/latest": dial tcp: lookup api.github.com: no such host
2021/04/02 11:01:20 [VersionChecker] stopping checker loop
2021/04/02 11:01:20 [notifier] existing notify loop
2021/04/02 11:01:20 [supervisor] rootSupervisor returns error: tree should be terminated
2021/04/02 11:01:20 [supervisor] signal received: terminated
2021/04/02 11:01:20 persist: closing "BatteryChargeLimit"
2021/04/02 11:01:20 persist: closing "ThermalProfile"
2021/04/02 11:01:20 persist: closing "KeyboardControl"
2021/04/02 11:01:20 persist: closing "Configs"
2021/04/02 11:01:20 persist: closing "Manager"

**Comment by zllovesuki** [comment]
Interesting, there are two problems:
1. version checker cannot connect to GitHub, which is fine as this is only for checking new version
2. somehow port 9963 on your local machine is in-used. This is needed for the future Configurator tool to change configuration. I will see what I can do to get around it.

**Comment by zllovesuki** [comment]
https://github.com/zllovesuki/G14Manager/releases/tag/v0.4.2 should allow you to use it for now. Although, I will work on making port conflict less of a problem in the future.
