### ISSUE TITLE
G14Manager version: v0.4.2 start up but not working

### ISSUE THREAD

**Issue by foxperience** [zllovesuki/G14Manager#70]
I lunch up G14Manager and below OSD is shown.

> Starting up G14Manager Supervisor
> A new version of G14Manager is available: 0.4.2

And then all G14Manager functions is not workinig. (e.g. Fn + Fxx key / Changing keyboard backlight)
I waited for 5 min, but log is not changed.

```

2021/04/02 16:25:37 G14Manager version: v0.4.2-debug
2021/04/02 16:25:37 [pprof] debugging server available at 127.0.0.1:41957
2021/04/02 16:25:37 [notifier] starting notify loop
2021/04/02 16:25:37 [gRPCSupervisor] starting responder loop
2021/04/02 16:25:37 [VersionChecker] starting checker loop
2021/04/02 16:25:37 [VersionChecker] checking for new version
2021/04/02 16:25:37 [gRPCServer] grpc server available at 127.0.0.1:41958
2021/04/02 16:25:37 persist: loading "BatteryChargeLimit" from the Registry
2021/04/02 16:25:37 persist: loading "ThermalProfile" from the Registry
2021/04/02 16:25:37 persist: loading "KeyboardControl" from the Registry
2021/04/02 16:25:37 persist: loading "Configs" from the Registry
2021/04/02 16:25:37 persist: loading "Manager" from the Registry
2021/04/02 16:25:38 [VersionChecker] new version found: 0.4.2

```

P.S. Thank you very much for your project! G14Manager is my favorite tool of all!

**Comment by zllovesuki** [comment]
ah, I forgot about the new version has to be started by gRPC. I will make some changes and keep you posted.

**Comment by zllovesuki** [comment]
Before I push a new release, try this version: 
[G14Manager.debug.zip](https://github.com/zllovesuki/G14Manager/files/6248375/G14Manager.debug.zip)

Also, before you run this, please open Registry Editor, and navigate to this: `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\G14Manager`, then delete the `Manager` entry.

**Comment by foxperience** [comment]
> Before I push a new release, try this version:
> [G14Manager.debug.zip](https://github.com/zllovesuki/G14Manager/files/6248375/G14Manager.debug.zip)
> 
> Also, before you run this, please open Registry Editor, and navigate to this: `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\G14Manager`, then delete the `Manager` entry.

Thank you!

I use test version  and tried some function and all works very well!
- Change display brightness
- Change keyboard backlight (OSD is displayed too)
- Change fan mode (OSD is displayed too)
- volume button
- mute / unmute button

Here is some log as proof.
<details>
<summary>G14Manager log</summary>
<pre>
<code>2021/04/02 17:47:05 G14Manager version: v0.0.0-debug
2021/04/02 17:47:05 [gRPCSupervisor] starting responder loop
2021/04/02 17:47:05 [pprof] debugging server available at 127.0.0.1:41957
2021/04/02 17:47:05 [VersionChecker] starting checker loop
2021/04/02 17:47:05 [notifier] starting notify loop
2021/04/02 17:47:05 [VersionChecker] checking for new version
2021/04/02 17:47:05 [gRPCServer] grpc server available at 127.0.0.1:41958
2021/04/02 17:47:05 persist: loading "BatteryChargeLimit" from the Registry
2021/04/02 17:47:05 persist: loading "ThermalProfile" from the Registry
2021/04/02 17:47:05 persist: loading "KeyboardControl" from the Registry
2021/04/02 17:47:05 persist: loading "Configs" from the Registry
2021/04/02 17:47:05 [gRPCServer] notifying "ThermalProfile" about features update
2021/04/02 17:47:05 [gRPCServer] notifying "ThermalProfile" about profiles update
2021/04/02 17:47:05 [gRPCServer] notifying "KeyboardControl" about features update
2021/04/02 17:47:05 [gRPCServer] notifying "KeyboardControl" about profiles update
2021/04/02 17:47:05 persist: loading "Manager" from the Registry
2021/04/02 17:47:05 [gRPCServer] set autoStart to true on new install
2021/04/02 17:47:05 [gRPCServer] auto starting controller
2021/04/02 17:47:05 [controller] Starting controller loop
2021/04/02 17:47:05 kbCtrl: initializaing hid interface
2021/04/02 17:47:05 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 137 0 0 0 0 0 0]
2021/04/02 17:47:05 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:47:05 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 65 83 85 83 32 84 101]
2021/04/02 17:47:05 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:47:05 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 5 32 49 0 8 0 0]
2021/04/02 17:47:05 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:47:05 volCtrl: current microphone mute is true
Available devices:
\\.\DISPLAY1 - AMD Radeon(TM) Graphics - 60 Hz - active - primary
\\.\DISPLAY2 - AMD Radeon(TM) Graphics - 0 Hz - inactive
\\.\DISPLAY3 - AMD Radeon(TM) Graphics - 0 Hz - inactive
\\.\DISPLAY4 - AMD Radeon(TM) Graphics - 0 Hz - inactive
\\.\DISPLAY5 - NVIDIA GeForce RTX 2060 with Max-Q Design - 0 Hz - inactive
\\.\DISPLAY6 - NVIDIA GeForce RTX 2060 with Max-Q Design - 0 Hz - inactive
\\.\DISPLAY7 - NVIDIA GeForce RTX 2060 with Max-Q Design - 0 Hz - inactive
\\.\DISPLAY8 - NVIDIA GeForce RTX 2060 with Max-Q Design - 0 Hz - inactive
Using:
\\.\DISPLAY1 - AMD Radeon(TM) Graphics - 60 Hz - active - primary
Supported Refresh Rates: 48 Hz 60 Hz
2021/04/02 17:47:05 hid: reading from \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
2021/04/02 17:47:05 hid: reading from \\?\hid#vid_0b05&pid_1866&mi_02&col02#8&1e16c781&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}
2021/04/02 17:47:05 power: registering suspend/resume notification
2021/04/02 17:47:05 device: \\.\ATKACPI (2237452) execute input buffer: [73 78 73 84 4 0 0 0 0 0 0 0]
2021/04/02 17:47:05 kbCtrl: Starting queue loop
2021/04/02 17:47:05 volCtrl: Starting queue loop
2021/04/02 17:47:05 thermal: Starting queue loop
2021/04/02 17:47:05 gpu: Starting queue loop
2021/04/02 17:47:05 rr: Starting queue loop
2021/04/02 17:47:05 persist: loading "BatteryChargeLimit" from the Registry
2021/04/02 17:47:05 persist: loading "ThermalProfile" from the Registry
2021/04/02 17:47:05 persist: loading "KeyboardControl" from the Registry
2021/04/02 17:47:05 persist: loading "Configs" from the Registry
2021/04/02 17:47:05 persist: loading "Manager" from the Registry
2021/04/02 17:47:05 [gRPCServer] set autoStart to true on new install
2021/04/02 17:47:05 persist: applying "BatteryChargeLimit" config
2021/04/02 17:47:05 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 87 0 18 0 50 0 0 0]
2021/04/02 17:47:05 persist: applying "ThermalProfile" config
2021/04/02 17:47:05 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 0 0 0 0]
2021/04/02 17:47:05 thermal: throttle plan set: 0x0
2021/04/02 17:47:05 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 20 0 0 0 36 0 17 0 20 50 55 60 65 70 75 98 0 0 0 0 31 49 56 56]
2021/04/02 17:47:05 thermal: cpu fan curve set to [20 50 55 60 65 70 75 98 0 0 0 0 31 49 56 56]
2021/04/02 17:47:05 [VersionChecker] new version found: 0.4.2
2021/04/02 17:47:06 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 20 0 0 0 37 0 17 0 20 50 55 60 65 70 75 98 0 0 0 0 34 51 61 61]
2021/04/02 17:47:06 thermal: gpu fan curve set to [20 50 55 60 65 70 75 98 0 0 0 0 34 51 61 61]
2021/04/02 17:47:06 windows power plan set to: Balanced
2021/04/02 17:47:06 persist: applying "KeyboardControl" config
2021/04/02 17:47:06 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 186 197 196 0 0 0 0]
2021/04/02 17:47:06 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:47:06 persist: applying "Configs" config
2021/04/02 17:47:06 [gRPCServer] notifying "ThermalProfile" about features update
2021/04/02 17:47:06 [gRPCServer] notifying "ThermalProfile" about profiles update
2021/04/02 17:47:06 [gRPCServer] notifying "KeyboardControl" about features update
2021/04/02 17:47:06 [gRPCServer] notifying "KeyboardControl" about profiles update
2021/04/02 17:47:06 persist: applying "Manager" config
2021/04/02 17:47:06 device: \\.\ATKACPI (2237452) execute input buffer: [68 83 84 83 4 0 0 0 108 0 18 0]
2021/04/02 17:47:06 [controller] 180W charger plugged in
2021/04/02 17:47:07 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 186 197 196 1 0 0 0]
2021/04/02 17:47:07 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:47:07 [gRPCServer] controller started
2021/04/02 17:47:08 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:47:08 persist: saving "Configs" to the Registry
2021/04/02 17:47:08 persist: saving "Manager" to the Registry
2021/04/02 17:47:08 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:47:08 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:47:10 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 186 197 196 0 0 0 0]
2021/04/02 17:47:10 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:47:11 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:47:11 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:47:11 persist: saving "Configs" to the Registry
2021/04/02 17:47:11 persist: saving "Manager" to the Registry
2021/04/02 17:47:11 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:47:30 hwCtrl: notification from keypress on 32
2021/04/02 17:47:30 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 32 0 0 0]
2021/04/02 17:47:31 hwCtrl: notification from keypress on 32
2021/04/02 17:47:31 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 32 0 0 0]
2021/04/02 17:47:31 hwCtrl: notification from keypress on 16
2021/04/02 17:47:31 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 16 0 0 0]
2021/04/02 17:47:32 hwCtrl: notification from keypress on 16
2021/04/02 17:47:32 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 16 0 0 0]
2021/04/02 17:47:32 hwCtrl: notification from keypress on 16
2021/04/02 17:47:32 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 16 0 0 0]
2021/04/02 17:47:32 hwCtrl: notification from keypress on 16
2021/04/02 17:47:32 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 16 0 0 0]
2021/04/02 17:47:32 hwCtrl: notification from keypress on 32
2021/04/02 17:47:32 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 32 0 0 0]
2021/04/02 17:47:32 hwCtrl: notification from keypress on 32
2021/04/02 17:47:32 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 32 0 0 0]
2021/04/02 17:47:33 hwCtrl: notification from keypress on 32
2021/04/02 17:47:33 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 32 0 0 0]
2021/04/02 17:47:33 hwCtrl: notification from keypress on 32
2021/04/02 17:47:33 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 32 0 0 0]
2021/04/02 17:47:33 hwCtrl: notification from keypress on 16
2021/04/02 17:47:33 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 16 0 0 0]
2021/04/02 17:47:33 hwCtrl: notification from keypress on 16
2021/04/02 17:47:33 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 16 0 0 0]
2021/04/02 17:47:34 hwCtrl: notification from keypress on 16
2021/04/02 17:47:34 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 16 0 0 0]
2021/04/02 17:47:35 hid: Fn + F5 Pressed (debounced)
2021/04/02 17:47:35 [controller] Fn + F5 pressed 1 times
2021/04/02 17:47:35 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 0 0 0 0]
2021/04/02 17:47:35 thermal: throttle plan set: 0x0
2021/04/02 17:47:35 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 20 0 0 0 36 0 17 0 20 50 55 60 65 70 75 98 10 10 10 10 31 49 56 56]
2021/04/02 17:47:35 thermal: cpu fan curve set to [20 50 55 60 65 70 75 98 10 10 10 10 31 49 56 56]
2021/04/02 17:47:36 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 20 0 0 0 37 0 17 0 20 50 55 60 65 70 75 98 0 0 0 0 34 51 61 61]
2021/04/02 17:47:36 thermal: gpu fan curve set to [20 50 55 60 65 70 75 98 0 0 0 0 34 51 61 61]
2021/04/02 17:47:37 hid: Fn + F5 Pressed (debounced)
2021/04/02 17:47:37 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:47:37 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:47:37 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:47:37 persist: saving "Configs" to the Registry
2021/04/02 17:47:37 persist: saving "Manager" to the Registry
2021/04/02 17:47:37 [controller] Fn + F5 pressed 1 times
2021/04/02 17:47:37 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 2 0 0 0]
2021/04/02 17:47:37 thermal: throttle plan set: 0x2
2021/04/02 17:47:38 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:47:38 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:47:38 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:47:38 persist: saving "Configs" to the Registry
2021/04/02 17:47:38 persist: saving "Manager" to the Registry
2021/04/02 17:47:38 hid: Fn + F5 Pressed (debounced)
2021/04/02 17:47:39 [controller] Fn + F5 pressed 1 times
2021/04/02 17:47:39 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 0 0 0 0]
2021/04/02 17:47:39 thermal: throttle plan set: 0x0
2021/04/02 17:47:39 windows power plan set to: High Performance
2021/04/02 17:47:40 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:47:40 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:47:40 persist: saving "Configs" to the Registry
2021/04/02 17:47:40 persist: saving "Manager" to the Registry
2021/04/02 17:47:40 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:47:41 hid: Fn + F5 Pressed (debounced)
2021/04/02 17:47:42 [controller] Fn + F5 pressed 1 times
2021/04/02 17:47:42 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 1 0 0 0]
2021/04/02 17:47:42 thermal: throttle plan set: 0x1
2021/04/02 17:47:43 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:47:43 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:47:43 persist: saving "Configs" to the Registry
2021/04/02 17:47:43 persist: saving "Manager" to the Registry
2021/04/02 17:47:43 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:47:43 hid: Fn + F5 Pressed (debounced)
2021/04/02 17:47:44 [controller] Fn + F5 pressed 1 times
2021/04/02 17:47:44 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 0 0 0 0]
2021/04/02 17:47:44 thermal: throttle plan set: 0x0
2021/04/02 17:47:44 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 20 0 0 0 36 0 17 0 20 50 55 60 65 70 75 98 0 0 0 0 31 49 56 56]
2021/04/02 17:47:44 thermal: cpu fan curve set to [20 50 55 60 65 70 75 98 0 0 0 0 31 49 56 56]
2021/04/02 17:47:44 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 20 0 0 0 37 0 17 0 20 50 55 60 65 70 75 98 0 0 0 0 34 51 61 61]
2021/04/02 17:47:44 thermal: gpu fan curve set to [20 50 55 60 65 70 75 98 0 0 0 0 34 51 61 61]
2021/04/02 17:47:44 windows power plan set to: Balanced
2021/04/02 17:47:45 persist: saving "Configs" to the Registry
2021/04/02 17:47:45 persist: saving "Manager" to the Registry
2021/04/02 17:47:45 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:47:45 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:47:45 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:47:45 hid: Fn + F5 Pressed (debounced)
2021/04/02 17:47:46 [controller] Fn + F5 pressed 1 times
2021/04/02 17:47:46 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 0 0 0 0]
2021/04/02 17:47:46 thermal: throttle plan set: 0x0
2021/04/02 17:47:46 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 20 0 0 0 36 0 17 0 20 50 55 60 65 70 75 98 10 10 10 10 31 49 56 56]
2021/04/02 17:47:46 thermal: cpu fan curve set to [20 50 55 60 65 70 75 98 10 10 10 10 31 49 56 56]
2021/04/02 17:47:46 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 20 0 0 0 37 0 17 0 20 50 55 60 65 70 75 98 0 0 0 0 34 51 61 61]
2021/04/02 17:47:46 thermal: gpu fan curve set to [20 50 55 60 65 70 75 98 0 0 0 0 34 51 61 61]
2021/04/02 17:47:47 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:47:47 persist: saving "Configs" to the Registry
2021/04/02 17:47:47 persist: saving "Manager" to the Registry
2021/04/02 17:47:47 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:47:47 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:47:50 hid: Fn + F5 Pressed (debounced)
2021/04/02 17:47:50 [controller] Fn + F5 pressed 1 times
2021/04/02 17:47:50 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 2 0 0 0]
2021/04/02 17:47:50 thermal: throttle plan set: 0x2
2021/04/02 17:47:52 persist: saving "Configs" to the Registry
2021/04/02 17:47:52 persist: saving "Manager" to the Registry
2021/04/02 17:47:52 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:47:52 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:47:52 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:49:36 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 186 197 196 1 0 0 0]
2021/04/02 17:49:36 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:49:36 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 186 197 196 0 0 0 0]
2021/04/02 17:49:36 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:49:36 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 186 197 196 1 0 0 0]
2021/04/02 17:49:36 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:49:37 hwCtrl: notification from keypress on 32
2021/04/02 17:49:37 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 32 0 0 0]
2021/04/02 17:49:37 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:49:37 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:49:37 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:49:37 persist: saving "Configs" to the Registry
2021/04/02 17:49:37 persist: saving "Manager" to the Registry
2021/04/02 17:49:37 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 186 197 196 0 0 0 0]
2021/04/02 17:49:37 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:49:38 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 186 197 196 1 0 0 0]
2021/04/02 17:49:38 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:49:38 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 186 197 196 0 0 0 0]
2021/04/02 17:49:38 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:49:38 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 186 197 196 1 0 0 0]
2021/04/02 17:49:38 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:49:39 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 186 197 196 0 0 0 0]
2021/04/02 17:49:39 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:49:40 hid: Fn + F5 Pressed (debounced)
2021/04/02 17:49:40 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:49:40 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:49:40 persist: saving "Configs" to the Registry
2021/04/02 17:49:40 persist: saving "Manager" to the Registry
2021/04/02 17:49:40 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:49:40 [controller] Fn + F5 pressed 1 times
2021/04/02 17:49:40 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 0 0 0 0]
2021/04/02 17:49:40 thermal: throttle plan set: 0x0
2021/04/02 17:49:40 windows power plan set to: High Performance
2021/04/02 17:49:41 hid: Fn + F5 Pressed (debounced)
2021/04/02 17:49:42 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:49:42 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:49:42 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:49:42 persist: saving "Configs" to the Registry
2021/04/02 17:49:42 persist: saving "Manager" to the Registry
2021/04/02 17:49:42 [controller] Fn + F5 pressed 1 times
2021/04/02 17:49:42 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 1 0 0 0]
2021/04/02 17:49:42 thermal: throttle plan set: 0x1
2021/04/02 17:49:43 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:49:43 persist: saving "Configs" to the Registry
2021/04/02 17:49:43 persist: saving "Manager" to the Registry
2021/04/02 17:49:43 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:49:43 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:49:43 hid: Fn + F5 Pressed (debounced)
2021/04/02 17:49:44 [controller] Fn + F5 pressed 1 times
2021/04/02 17:49:44 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 117 0 18 0 0 0 0 0]
2021/04/02 17:49:44 thermal: throttle plan set: 0x0
2021/04/02 17:49:44 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 20 0 0 0 36 0 17 0 20 50 55 60 65 70 75 98 0 0 0 0 31 49 56 56]
2021/04/02 17:49:44 thermal: cpu fan curve set to [20 50 55 60 65 70 75 98 0 0 0 0 31 49 56 56]
2021/04/02 17:49:44 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 20 0 0 0 37 0 17 0 20 50 55 60 65 70 75 98 0 0 0 0 34 51 61 61]
2021/04/02 17:49:44 thermal: gpu fan curve set to [20 50 55 60 65 70 75 98 0 0 0 0 34 51 61 61]
2021/04/02 17:49:44 windows power plan set to: Balanced
2021/04/02 17:49:45 persist: saving "BatteryChargeLimit" to the Registry
2021/04/02 17:49:45 persist: saving "ThermalProfile" to the Registry
2021/04/02 17:49:45 persist: saving "KeyboardControl" to the Registry
2021/04/02 17:49:45 persist: saving "Configs" to the Registry
2021/04/02 17:49:45 persist: saving "Manager" to the Registry
2021/04/02 17:49:47 hwCtrl: notification from keypress on 32
2021/04/02 17:49:47 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 32 0 0 0]
2021/04/02 17:49:47 hwCtrl: notification from keypress on 16
2021/04/02 17:49:47 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 16 0 0 0]
2021/04/02 17:50:27 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 244 107 0 0 0 0 0]
2021/04/02 17:50:27 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:50:29 device: \\?\hid#vid_0b05&pid_1866&mi_02&col01#8&1e16c781&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} (721297) write input buffer [0:8]: [90 244 107 0 0 0 0 0]
2021/04/02 17:50:29 device: write output buffer [0:8]: [0 0 0 0 0 0 0 0]
2021/04/02 17:50:31 volCtrl: setting microphone mute to false
2021/04/02 17:50:32 volCtrl: setting microphone mute to true
2021/04/02 17:50:36 hid: volume down Pressed
2021/04/02 17:50:37 hid: volume up Pressed
2021/04/02 17:50:37 hid: volume down Pressed
2021/04/02 17:50:37 hid: volume down Pressed
2021/04/02 17:50:37 hid: volume down Pressed
2021/04/02 17:50:38 hid: volume down Pressed
2021/04/02 17:50:38 hid: volume down Pressed
2021/04/02 17:50:38 hid: volume up Pressed
2021/04/02 17:50:38 hid: volume up Pressed
2021/04/02 17:50:38 hid: volume up Pressed
2021/04/02 17:50:39 hid: volume up Pressed
2021/04/02 17:50:39 hid: volume up Pressed
2021/04/02 17:52:29 hwCtrl: notification from keypress on 32
2021/04/02 17:52:29 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 32 0 0 0]
2021/04/02 17:52:49 hwCtrl: notification from keypress on 16
2021/04/02 17:52:49 device: \\.\ATKACPI (2237452) execute input buffer: [68 69 86 83 8 0 0 0 33 0 16 0 16 0 0 0]
</code>
</pre>
</details>

**Comment by foxperience** [comment]
Also, I tried "G14Manager version: v0.4.3", it's works great too!

**Comment by zllovesuki** [comment]
No problem. I plan to add an UI for configuration. Stay tuned.
